name: Python package
on:
  push:
  pull_request:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dev dependencies
        run:  pip install -r requirements_test.txt
      - name: Run Linter
        run:  |
              echo "## flake8 !"
              /opt/conda/envs/python_indus_avancee/bin/flake8 --verbose formation_indus_ds_avancee
      - name: Run Vulture
        run:  |
               echo "## vulture !"
               /opt/conda/envs/python_indus_avancee/bin/vulture --verbose formation_indus_ds_avancee
      - name: Run tests
        run:  |
              echo "## tests !"
              make tests-unitaires


